# HW3 Support Vector Machine and Decision Trees

# Due on 11/30 23:59 pm

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## We will use the same affair dataset from HW2, but will skip the EDA phrase we have done enough of it

#### Everything removing outliers, create dummies variabes had been done for you

In [2]:
# Remember the affair data set from HW3, we will use that dataset again
# but we will directly load from file
orig_df = pd.read_csv("affairs2.csv")
# Set up our target class label
orig_df['had_affair'] = orig_df['affairs'].apply(lambda x: 1 if x != 0 else 0)
orig_df = orig_df.drop('affairs',axis=1)
# remove NA
orig_df.dropna(inplace=True)
# create dummies variable for occupation
occ = pd.get_dummies(orig_df['occupation'],drop_first=True)
# we include rate_marriage feature as well. In HW3, we did not include that variable
features = ['rate_marriage','age','yrs_married','children','religious','educ', 'had_affair']
df = orig_df
df = pd.concat([orig_df[features], occ], axis=1)
df.head()

rate_marriage   age  yrs_married  children  religious  educ  had_affair  \
0            3.0  32.0          9.0       3.0        3.0  17.0           1   
1            3.0  27.0         13.0       3.0        1.0  14.0           1   
2            4.0  22.0          2.5       0.0        1.0  16.0           1   
3            4.0  37.0         16.5       4.0        3.0  16.0           1   
4            5.0  27.0          9.0       1.0        1.0  14.0           1   

   occ2  occ3  occ4  occ5  occ6  
0     1     0     0     0     0  
1     0     1     0     0     0  
2     0     1     0     0     0  
3     0     0     0     1     0  
4     0     1     0     0     0

In [3]:
# make sure there is no missing values
df.isnull().sum()

rate_marriage    0
age              0
yrs_married      0
children         0
religious        0
educ             0
had_affair       0
occ2             0
occ3             0
occ4             0
occ5             0
occ6             0
dtype: int64

### Now we are ready to build models

### Question 1: Build a classification model using SVC using linear kernel with usual steps

In [4]:
#separate the data set into two sets: set of features and a set of taarget varibles
X = df.to_numpy()
X

array([[ 3. , 32. ,  9. , ...,  0. ,  0. ,  0. ],
       [ 3. , 27. , 13. , ...,  0. ,  0. ,  0. ],
       [ 4. , 22. ,  2.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 5. , 22. ,  2.5, ...,  0. ,  0. ,  0. ],
       [ 5. , 32. ,  6. , ...,  0. ,  0. ,  0. ],
       [ 4. , 22. ,  2.5, ...,  0. ,  0. ,  0. ]])

In [5]:
Y = df['had_affair'].to_numpy()
Y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [6]:
#import the model from sklearn import svm, create the SVC object 
from sklearn.model_selection import train_test_split

In [7]:
#Call Train test split
X_train, X_test, Y_train, Y_test = train_test_split(df.drop('had_affair', axis = 1), df['had_affair'], test_size = 0.2, random_state = 2)

In [8]:
from sklearn import svm

In [9]:
#model = svm.SVC()
model_1 = svm.SVC(kernel = 'linear', C=1)
model_1.fit(X_train, Y_train)

SVC(C=1, kernel='linear')

In [10]:
model_1_y_pred = model_1.predict(X_test)
model_1_y_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
#print out model performance
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
model_1_predictions = model_1.predict(X_test)
print(confusion_matrix(Y_test, model_1_predictions))
print(classification_report(Y_test, model_1_predictions))
print(accuracy_score(Y_test, model_1_predictions))

[[797  56]
 [303 118]]
              precision    recall  f1-score   support

           0       0.72      0.93      0.82       853
           1       0.68      0.28      0.40       421

    accuracy                           0.72      1274
   macro avg       0.70      0.61      0.61      1274
weighted avg       0.71      0.72      0.68      1274

0.7182103610675039


### Question 2. Now try different value of C-parameter and rerun your model

In [12]:
# Try C = 2**-5 

In [13]:
model_2 = svm.SVC(kernel='linear', C = 2**-5)
model_2.fit(X_train, Y_train)

SVC(C=0.03125, kernel='linear')

In [14]:
model_2_y_pred = model_2.predict(X_test)
model_2_y_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
model_2_predictions = model_2.predict(X_test)
print(confusion_matrix(Y_test, model_2_predictions))
print(classification_report(Y_test, model_2_predictions))
print(accuracy_score(Y_test, model_2_predictions))

[[799  54]
 [308 113]]
              precision    recall  f1-score   support

           0       0.72      0.94      0.82       853
           1       0.68      0.27      0.38       421

    accuracy                           0.72      1274
   macro avg       0.70      0.60      0.60      1274
weighted avg       0.71      0.72      0.67      1274

0.7158555729984302


In [16]:
# Try C = 2**5

In [17]:
model_3 = svm.SVC(kernel='linear', C = 2**5)
model_3.fit(X_train, Y_train)

SVC(C=32, kernel='linear')

In [18]:
model_3_y_pred = model_2.predict(X_test)
model_3_y_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
model_3_predictions = model_3.predict(X_test)
print(confusion_matrix(Y_test, model_3_predictions))
print(classification_report(Y_test, model_3_predictions))
print(accuracy_score(Y_test, model_3_predictions))

[[797  56]
 [302 119]]
              precision    recall  f1-score   support

           0       0.73      0.93      0.82       853
           1       0.68      0.28      0.40       421

    accuracy                           0.72      1274
   macro avg       0.70      0.61      0.61      1274
weighted avg       0.71      0.72      0.68      1274

0.7189952904238619


### Question 3. Try using rbf as your kernel and use Gamma of 2**-5, 0.1, 1 and 2

In [20]:
# model with rbf for kernel and 2^(-5) for Gamma
kernel_model_1 = svm.SVC(kernel='rbf', gamma = 2**-5)
kernel_model_1.fit(X_train, Y_train)

SVC(gamma=0.03125)

In [21]:
y_kernel1_pred = kernel_model_1.predict(X_test)
y_kernel1_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
kernel_model_1_predictions = kernel_model_1.predict(X_test)
print(confusion_matrix(Y_test, kernel_model_1_predictions))
print(classification_report(Y_test, kernel_model_1_predictions))
print(accuracy_score(Y_test, kernel_model_1_predictions))

[[786  67]
 [288 133]]
              precision    recall  f1-score   support

           0       0.73      0.92      0.82       853
           1       0.67      0.32      0.43       421

    accuracy                           0.72      1274
   macro avg       0.70      0.62      0.62      1274
weighted avg       0.71      0.72      0.69      1274

0.7213500784929356


In [23]:
# model with rbf for kernel and 0.1 for Gamma

In [24]:
kernel_model_2 = svm.SVC(kernel='rbf', gamma = 0.1)
kernel_model_2.fit(X_train, Y_train)

SVC(gamma=0.1)

In [25]:
y_kernel2_pred = kernel_model_2.predict(X_test)
y_kernel2_pred

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
kernel_model_2_predictions = kernel_model_2.predict(X_test)
print(confusion_matrix(Y_test, kernel_model_2_predictions))
print(classification_report(Y_test, kernel_model_2_predictions))
print(accuracy_score(Y_test, kernel_model_2_predictions))

[[777  76]
 [278 143]]
              precision    recall  f1-score   support

           0       0.74      0.91      0.81       853
           1       0.65      0.34      0.45       421

    accuracy                           0.72      1274
   macro avg       0.69      0.63      0.63      1274
weighted avg       0.71      0.72      0.69      1274

0.7221350078492935


In [27]:
# model with rbf for kernel and 1 for Gamma

In [28]:
kernel_model_3 = svm.SVC(kernel='rbf', gamma = 1)
kernel_model_3.fit(X_train, Y_train)

SVC(gamma=1)

In [29]:
y_kernel3_pred = kernel_model_3.predict(X_test)
y_kernel3_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
kernel_model_3_predictions = kernel_model_3.predict(X_test)
print(confusion_matrix(Y_test, kernel_model_3_predictions))
print(classification_report(Y_test, kernel_model_3_predictions))
print(accuracy_score(Y_test, kernel_model_3_predictions))

[[770  83]
 [325  96]]
              precision    recall  f1-score   support

           0       0.70      0.90      0.79       853
           1       0.54      0.23      0.32       421

    accuracy                           0.68      1274
   macro avg       0.62      0.57      0.56      1274
weighted avg       0.65      0.68      0.64      1274

0.6797488226059655


In [31]:
# model with rbf for kernel and 2 for Gamma

In [32]:
kernel_model_4 = svm.SVC(kernel='rbf', gamma = 2)
kernel_model_4.fit(X_train, Y_train)

SVC(gamma=2)

In [33]:
y_kernel4_pred = kernel_model_4.predict(X_test)
y_kernel4_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
kernel_model_4_predictions = kernel_model_4.predict(X_test)
print(confusion_matrix(Y_test, kernel_model_4_predictions))
print(classification_report(Y_test, kernel_model_4_predictions))
print(accuracy_score(Y_test, kernel_model_4_predictions))

[[781  72]
 [371  50]]
              precision    recall  f1-score   support

           0       0.68      0.92      0.78       853
           1       0.41      0.12      0.18       421

    accuracy                           0.65      1274
   macro avg       0.54      0.52      0.48      1274
weighted avg       0.59      0.65      0.58      1274

0.652276295133438


### Question 4. So out of all the models you try in Question 2 and 3, what is the best choice for the kernel, C and gamma parameters?

<strong>Linear</strong> kernel is better in comparison with <em>Radial Basis Function</em> according to the performance of the models obtained above. Since we have only two classes, we it is enough to use linear kernel to get proper results.

C parameter is the penalty representing misclassification or error. A small value of C creates a small-margin hyperplane and a larger value of C creates a lerger-marging hyperplane. Based on the results obtained above, the largest value of C, in our case it is <strong>32 (2^5)</strong>, is the best choice.

In our case there are two best value for gamma. They are <strong>2^(-5)</strong> and <strong>0.1</strong>. Yet, it considers only nearby points in calculating the separation line in contrast to the large values of gamma that consider all the data points in the calculation of the separation line.

# Now we will try to fit the same dataset with Decision Trees

### Question 5. Build a Decision Tree Classifier using default parameter

In [35]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [36]:
model_default_predictions = model.predict(X_test)
print(confusion_matrix(Y_test, model_default_predictions))
print(classification_report(Y_test, model_default_predictions))
print(accuracy_score(Y_test, model_default_predictions))

[[676 177]
 [275 146]]
              precision    recall  f1-score   support

           0       0.71      0.79      0.75       853
           1       0.45      0.35      0.39       421

    accuracy                           0.65      1274
   macro avg       0.58      0.57      0.57      1274
weighted avg       0.63      0.65      0.63      1274

0.6452119309262166


### Question 6. Now try using max_depth = 2, 3, 4 and crierion = 'gini' and 'entropy' to build 3 X 2 = 6 different models

In [37]:
# Decision Tree with max depth = 2 and GINI for criterion
g2_model = DecisionTreeClassifier(criterion = 'gini', max_depth = 2)
g2_model.fit(X_train,Y_train)
g2_model_predictions = g2_model.predict(X_test)
print(confusion_matrix(Y_test, g2_model_predictions))
print(classification_report(Y_test, g2_model_predictions))
print(accuracy_score(Y_test, g2_model_predictions))

[[772  81]
 [279 142]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       853
           1       0.64      0.34      0.44       421

    accuracy                           0.72      1274
   macro avg       0.69      0.62      0.63      1274
weighted avg       0.70      0.72      0.69      1274

0.717425431711146


In [38]:
# Decision Tree with max depth = 2 and ENTROPY for criterion
e2_model = DecisionTreeClassifier(criterion = 'entropy', max_depth = 2)
e2_model.fit(X_train,Y_train)
e2_model_predictions = e2_model.predict(X_test)
print(confusion_matrix(Y_test, e2_model_predictions))
print(classification_report(Y_test, e2_model_predictions))
print(accuracy_score(Y_test, e2_model_predictions))

[[772  81]
 [279 142]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       853
           1       0.64      0.34      0.44       421

    accuracy                           0.72      1274
   macro avg       0.69      0.62      0.63      1274
weighted avg       0.70      0.72      0.69      1274

0.717425431711146


In [39]:
# Decision Tree with max depth = 3 and GINI for criterion
g3_model = DecisionTreeClassifier(criterion = 'gini', max_depth = 3)
g3_model.fit(X_train,Y_train)
g3_model_predictions = g3_model.predict(X_test)
print(confusion_matrix(Y_test, g3_model_predictions))
print(classification_report(Y_test, g3_model_predictions))
print(accuracy_score(Y_test, g3_model_predictions))

[[787  66]
 [298 123]]
              precision    recall  f1-score   support

           0       0.73      0.92      0.81       853
           1       0.65      0.29      0.40       421

    accuracy                           0.71      1274
   macro avg       0.69      0.61      0.61      1274
weighted avg       0.70      0.71      0.68      1274

0.7142857142857143


In [40]:
# Decision Tree with max depth = 3 and ENTROPY for criterion
e3_model = DecisionTreeClassifier(criterion = 'entropy', max_depth = 3)
e3_model.fit(X_train,Y_train)
e3_model_predictions = e3_model.predict(X_test)
print(confusion_matrix(Y_test, e3_model_predictions))
print(classification_report(Y_test, e3_model_predictions))
print(accuracy_score(Y_test, e3_model_predictions))

[[787  66]
 [298 123]]
              precision    recall  f1-score   support

           0       0.73      0.92      0.81       853
           1       0.65      0.29      0.40       421

    accuracy                           0.71      1274
   macro avg       0.69      0.61      0.61      1274
weighted avg       0.70      0.71      0.68      1274

0.7142857142857143


In [41]:
# Decision Tree with max depth = 4 and GINI for criterion
g4_model = DecisionTreeClassifier(criterion = 'gini', max_depth = 4)
g4_model.fit(X_train,Y_train)
g4_model_predictions = g4_model.predict(X_test)
print(confusion_matrix(Y_test, g4_model_predictions))
print(classification_report(Y_test, g4_model_predictions))
print(accuracy_score(Y_test, g4_model_predictions))

[[772  81]
 [282 139]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       853
           1       0.63      0.33      0.43       421

    accuracy                           0.72      1274
   macro avg       0.68      0.62      0.62      1274
weighted avg       0.70      0.72      0.69      1274

0.7150706436420722


In [42]:
# Decision Tree with max depth = 4 and ENTROPY for criterion
e4_model = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)
e4_model.fit(X_train,Y_train)
e4_model_predictions = e4_model.predict(X_test)
print(confusion_matrix(Y_test, e4_model_predictions))
print(classification_report(Y_test, e4_model_predictions))
print(accuracy_score(Y_test, e4_model_predictions))

[[772  81]
 [282 139]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       853
           1       0.63      0.33      0.43       421

    accuracy                           0.72      1274
   macro avg       0.68      0.62      0.62      1274
weighted avg       0.70      0.72      0.69      1274

0.7150706436420722


### Question 7. What is your obsevation from Question 6? Does the choice of the criterion important in this case? What about the max_depth? What is the best choice of max_depth and criterion?

Answer: Since performance of models using gini and entropy for criterion are identical for each model with the same depth, the choice of criterion does not make a difference in performance.

As for the value of depth, the best performance is obtained with the value of 2

## Tree Visualization

Scikit learn actually has some built-in visualization capabilities for decision trees, you won't use this often and it requires you to install the pydot library, but here is an example of what it looks like and the code to execute this:

In [43]:
df.columns

Index(['rate_marriage', 'age', 'yrs_married', 'children', 'religious', 'educ',
       'had_affair', 'occ2', 'occ3', 'occ4', 'occ5', 'occ6'],
      dtype='object')

In [44]:
features

['rate_marriage',
 'age',
 'yrs_married',
 'children',
 'religious',
 'educ',
 'had_affair']

In [45]:
#from sklearn.externals.six import StringIO
from six import StringIO

In [46]:
from sklearn.tree import export_graphviz

In [47]:
from IPython.display import Image  
# from sklearn.externals.six import StringIO  
from sklearn.tree import export_graphviz
import io
import pydot 

# Pick up all featurs columns from your data frame
features = list(df.drop(['had_affair'],axis=1).columns)
features

['rate_marriage',
 'age',
 'yrs_married',
 'children',
 'religious',
 'educ',
 'occ2',
 'occ3',
 'occ4',
 'occ5',
 'occ6']

In [ ]:
# general tree representation
dot_data = StringIO()
export_graphviz(model, out_file=dot_data, feature_names=features)
(graph, ) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

### Question 8, now pick three models, with max_depth = 2, 3 and 4. You can pick the which ever criterions you want and visual the three trees

In [ ]:
# tree with depth 2 and entropy for criterion
dot_data = StringIO()
export_graphviz(e2_model, out_file=dot_data, feature_names=features, filled=True, rounded = True)
(graph, ) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

In [ ]:
# tree with depth 3 and gini for criterion
dot_data = StringIO()
export_graphviz(g3_model, out_file=dot_data, feature_names=features, filled=True, rounded = True)
(graph, ) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

In [ ]:
# tree with depth 2 and entropy for criterion
dot_data = StringIO()
export_graphviz(e4_model, out_file=dot_data, feature_names=features, filled=True, rounded = True)
(graph, ) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

### Question 9. Now build a Random Forest Classifier with, say, 100 trees. Check the model performance 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 100)
rfc.fit(X_train, Y_train)

In [ ]:
rfc_pred = rfc.predict(X_test)
print(classification_report(Y_test, e2_model_predictions))
print(accuracy_score(Y_test, e2_model_predictions))

In [ ]:
print(classification_report(Y_test, g3_model_predictions))
print(accuracy_score(Y_test, g3_model_predictions))

In [ ]:
print(classification_report(Y_test, e4_model_predictions))
print(accuracy_score(Y_test, e4_model_predictions))

The random forest for model with tree depth = 2 and entropy for criterion displays the best model performance.